name: nimble_charts
version: 0.12.0
description: Charts for Flutter. A fork of charts_flutter
homepage: https://github.com/MelbourneDeveloper/charts

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  nimble_charts_common:
    path: ../charts_common/
  collection: ^1.14.5
  flutter:
    sdk: flutter
  intl: ^0.19.0
  logging: ^1.0.2
  meta: ^1.1.1


dev_dependencies:
  mockito: ^5.0.0
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  test: ^1.3.0
